config/routes.rb
Rails.application.routes.draw do
  resources :puppies do
    resources :suggestions, only: [:create]
  end

  root 'puppies#index'

end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
	has_many :suggestions
	validates :owner, presence:true
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
	belongs_to :puppy
	validates :name, presence:true
	validates :puppy, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
# rest methods are from config/routes
class PuppiesController < ApplicationController
	respond_to :html
	before_action :find_puppy, except:[:index, :new, :create]
	def index
		# load puppies using Active Record
		# render view that is in view method
		@puppies = Puppy.all
		respond_with @puppies

	end
	def show
		respond_with @puppy
	end

	# named the same as the action
	def new
		@puppy = Puppy.new
		respond_with @puppy
	end

	# forbidden attributes - can tell model what attr are forbidden and what are not
	def create
		@puppy = Puppy.create(puppy_params)
		respond_with @puppy
	end

	def edit
		respond_with @puppy
	end
	def update 
		@puppy.update(puppy_params)
		respond_with @puppy
	end 
	def destroy
		@puppy.destroy()
		respond_with @puppy
	end

	private

	def puppy_params
		params.require(:puppy).permit(:owner, :description, :color)
	end

	def find_puppy
		@puppy = Puppy.find(params[:id])
	end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
	respond_to :html
	before_action find_puppy
	def create
		@suggestion = @puppy.suggestions.create(suggestion_params)

		respond_with @suggestion, location:puppy_url(@puppy)
	end

	private
	def suggestion_params
		params.require(:suggestion).permit(:name)
	end

	def find_puppy
		@puppy = Puppy.find(params[:puppy_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Corgi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puppies/_form.html.erb
<!-- f is the form definition proxy for the form  -->
<% unless @puppy.errors.empty? %>
<h2>Errors</h2>
	<ul>
		<% @puppy.errors.full_messages.each do |error| %>
			<li><%=error %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @puppy do |f|%>
	<p> Owner name: <%= f.text_field :owner %> </p>
	<p> Color: <%= f.text_field :color %> </p>
	<p> Description </p>
	<%= f.text_area :description %> 
	<p><%= f.submit %></p>

<% end %>

app/views/puppies/edit.html.erb
<h1> Edit Puppy <h1>
<%= render partial: 'form'%>

app/views/puppies/index.html.erb
<h1>Puppies</h1>
	<ul>
		<% @puppies.each do |puppy| %>
			<li>
				Puppy owned by <%= puppy.owner%>
				<% if puppy.color? %>
					(color <%= puppy.color%>)
				<%end%>
				<%= link_to "More info", puppy_url(puppy) %>
			</li>
		<% end %>
	</ul>

	<p><%= link_to "Add a new puppy", new_puppy_url%></p>

app/views/puppies/new.html.erb
<h1>Add new puppy</h1>
<%= render partial: 'form' %>

app/views/puppies/show.html.erb
<h1> Puppy owned by <%= @puppy.owner %></h1>
<ul>
	<% @puppy.suggestions.each do |suggestion| %>
		<li> <%= suggestion.name %> </li>
	<% end %>
</ul>

<%= form_for [@puppy,@puppy.suggestions.build] do |f| %>
	<p> Suggestion: <%=f.text_field :name, required:true %> <%=f.submit%> </p>
<% end %>

<p><%= link_to "Edit", edit_puppy_url(@puppy)%></p>